project:
  type: book
  output-dir: docs

execute: 
  echo: true
  warning: false
  message: false
  
book:
  title: "Hiram: ECE244 Tidy Notes"
  chapters:
    - index.qmd
    - lecture1.qmd
    - lecture2.qmd
    - lecture3.qmd
    - lecture4.qmd
    - lecture5.qmd
    - lecture6.qmd
    - lecture7.qmd
    - lecture8.qmd
    - lecture9.qmd
    - lecture10.qmd
    - lecture11.qmd
    
format:
  html:
    theme: [cosmo]
    number-sections: false