project:
  type: book
  output-dir: docs

execute: 
  echo: true
  warning: false
  message: false
  
book:
  title: "Hiram: ECE244 Tidy Notes"
  chapters:
    - index.qmd
    - lecture1.qmd
    - lecture2.qmd
    - lecture3.qmd
    - lecture4.qmd
    - lecture5.qmd
    - lecture6.qmd
    - lecture7.qmd
    - lecture8.qmd
    - lecture9.qmd
    - lecture10.qmd
    - lecture11.qmd
    - lecture12.qmd
    - lecture13.qmd
    - lecture14.qmd
    - lecture15.qmd
    - lecture16.qmd
    - lecture17.qmd
    - lecture18.qmd
    - lecture19.qmd
    - lecture20.qmd
    - lecture21.qmd
    - lecture22.qmd
    - lecture23.qmd
    - lecture24.qmd
    - lecture25.qmd
    - lecture26.qmd
    - lecture27.qmd
    - lecture28.qmd
    - lecture29.qmd
    - lecture30.qmd
    - lecture31.qmd
    - lecture32.qmd
    - lecture33.qmd
    - lecture34.qmd
    - lecture35.qmd
    - lecture36.qmd

format:
  html:
    theme: [cosmo]
    number-sections: false
    