## Introduction

### Why Hiram?

Professor Emara is from Egypt and she is also a master programmer. She titled
her notes Snefru and Khufu (C and C++, respectively).

Because I am learning from her and I come from Political Science, I am like
Hiram, a blacksmith from Tyre (today's Lebanon) who learned stone masonry from
master craftsmen from Egypt.

### About ECE244 - Programming Fundamentals

This course provides a foundation in programming using an object-oriented
programming language. Topics include classes and objects, inheritance,  basic
data structures (lists, tree, hash tables, etc.), Big-O complexity analysis, and
testing and debugging. The laboratory assignments emphasize the use of
object-oriented programming constructs in the design and implementation of
reasonably large programs.

### In memoriam

While tidying these notes, it was impossible not to go back to the many talks
about mathematics with Prof. Luis Armando Dissett Vélez (1963-2021), who always
answered my questions about convex separation properties, and I always ended up
knowing more than I wanted to know about different theorems of the alternative
and connections from calculus to statistics to graph theory. I will always
remember him as a great teacher and a great person that truly represented the
values of the Pontificia Universidad Católica de Chile.

### Pacha's notes

* The notes are 100% adjusted to the class.
* In the snippets folder, I have included some (unofficial) code snippets with
 the same examples from the notes, that I use to check if the code compiles.
* Some of the examples in the notes have small additions, such as
 `using namespace std;` or `#include <iostream>`, to make them compile.
* The diagrams are kinda ugly, my apologies! I'm not a graphic designer.
